### ISSUE TITLE
Compensations / repas bénévole

### ISSUE THREAD

**Issue by peufo** [peufo/benev#17]
retour Patricia : 

> Est-ce qu’on pourrait avoir une page qui récapitule les repas auxquels chaque bénévole est inscrit ?
> Et pour les responsables, la possibilité d’inscrire ses bénévoles au repas ?
> Et pour le cuisinier, une liste des personnes qui mangent, par repas, avec les intolérances
> alimentaires en évidence ?

**Comment by peufo** [comment]
Ouah, c'est un sacré morceau.

Il faut réfléchir à un système de compensation...

On va prioriser le développement de la vue d'ensemble avec un téléchargement des données #10 .

**Comment by Patriedweg** [comment]
Hello, on se prend bien la tête sur les compensations. Je pense que la vue d'ensemble nous sera très utile pour les repas. Ensuite pour les entrées aux concerts, on pensait: Toutes les personnes qui font 8h de montage ont le droit de venir le jour de leur choix MAIS il faut qu'elles s'annoncent pour avoir une place. Donc soit je gère ça par mail, soit tu as une idée lumineuse d'un truc pas trop compliqué à programmer. Ensuite, les autres secteurs peuvent voir les concerts le jour de leur bénévolat mais pareil, il faudrait que les gens s'annoncent pour ne pas bloquer des places si les gens ne viennent pas. Et pour les repas finalement c'est pareil, il faudrait leur dire à quoi ils ont le droit (1 tranche horaire=1 repas) et ensuite qu'ils aient la possibilité de s'inscrire ou non. Et de notre côté, il faudrait qu'on ait une liste de nom pour chaque concert et chaque repas. Mais franchement la plateforme comme ça elle est déjà super donc si C'est chiant on peut aussi faire autrement. Merci !!!

**Comment by Patriedweg** [comment]
Pour les compensations, je me dis que je pourrais rajouter deux champs dans les profils des membres visibles par eux mais pas modifiables par eux. Un champ repas avec les repas auxquels ils ont droit et un champ concerts avec les concerts auxquels ils ont droit. Et le tour est joué, non ? Et si on peut faire en sorte que ces champs soient des filtres, on peut savoir le nombre d'invitations pour chaque concert et le nombre de repas pour chaque repas. ça te paraît bien ou je fatigue et je passe à côté d'un gros problème?

**Comment by Patriedweg** [comment]
Salut ! Qu'est-ce que tu penses de mon idées ? Il y a des bénévoles qui posent des questions et j'aimerais bien pouvoir leur montrer à quoi ils ou elles ont droit :-)

**Comment by peufo** [comment]
Hello, je suis passé a côté du message.
Ca me parait parfaitement adapté et c'est un super exemple d'utilisation des champs libre.
Faudra mettre les champs à jour manuellement mais ca me semble être une solution simple et flexible.

**Comment by peufo** [comment]
C'est sur la synthèse qu'il y a du boulot.
Elle doit être personnalisable

**Comment by Patriedweg** [comment]
oui pour les compensations on doit de toute façon faire à la main ! Car il y a des gens qui vont avoir droit à certaines compensations mais ne seront pas dispos pour en profiter. Donc très bien comme ça !

**Comment by Patriedweg** [comment]
Pour la synthèse, en effet, il peut y avoir du boulot. J'ai des idées mais peut-être que pour la première édition on peut faire simple surtout si les changements risquent de créer des bugs.

**Comment by Patriedweg** [comment]
Pour les repas, je ferai aussi un champ supplémentaire complété à la main. Est-ce qu'il pourrait y avoir ensuite la possibilité de changer l'ordre des champs :-)  ?

**Comment by Patriedweg** [comment]
Pour les compensations, quand on a une liste à choix multiples on a les résultats avec les différentes option combinées. Ce qui est super pour les végétariens qui sont aussi sans gluten mais moins pour ceux qui ont le concert du jeudi et celui du dimanche. Si on pouvait avoir l'option de choisir si on affiche les résultat en empilement ou le nombre d'occurrences par résultat ce serait topissime.

**Comment by peufo** [comment]
> Pour la synthèse, en effet, il peut y avoir du boulot. J'ai des idées mais peut-être que pour la première édition on peut faire simple surtout si les changements risquent de créer des bugs. Et pour moi ça va avec la https://github.com/peufo/benev/issues/40

L'issue #40 sera le prochain gros morceau.
Je ne pense pas qu'il faille ce faire de soucis au niveau des bugs, Il y a eu des changement en profondeur pour les dernières fonctionnalités que j'ai implémenté. La il s'agit plus de mise à jour qui ne concerne que la partie lecture admin.
Je serai également un peu plus prudent ; )

> Pour les repas, je ferai aussi un champ supplémentaire complété à la main. Est-ce qu'il pourrait y avoir ensuite la possibilité de changer l'ordre des champs :-) ?

Nouvelle issue #68.

Je ferme celle-ci le problème semble résolue.
