### ISSUE TITLE
Suppression / désactivation du compte

### ISSUE THREAD

**Issue by peufo** [peufo/benev#28]

**Comment by Patriedweg** [comment]
Un bénévole m'a demandé de supprimer son compte
Me desinscrir stp et totalement effacer mon compte stp
C'est Jonas Weber
Est-ce que tu peux le faire ? Je n'arrive pas à le faire.
Merci !

**Comment by peufo** [comment]
La fonctionnalité n'existe pas encore, je m'en occupe à la main

**Comment by peufo** [comment]
C'est fait

**Comment by Patriedweg** [comment]
Merci!
