### ISSUE TITLE
Coordonnées du responsable visibles par le bénévole 

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#34]
Est-ce qu’on peut mettre les logos mails et téléphone à côté du nom du responsable afin que le bénévole puisse le joindre facilement?

**Comment by peufo** [comment]
Hello,
C'est fait, quand on clique sur un bénévole, on a un petit menu de contact qui s'affiche.

**Comment by Patriedweg** [comment]
Comment on fait pour mettre un responsable étant donné qu'il n'y a plus de responsable enregistré'
