### ISSUE TITLE
Vue d'ensemble organisateur: vue bénévole

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#35]
Pouvoir extraire des données de la base de données. Par exemple voir toutes les tranches horaire d’un bénévole.

**Comment by peufo** [comment]
Cette vue est prévu quand tu clique sur un bénévole depuis la vue d'ensemble des bénévoles: (https://benev.ch/spiegelberg-festival/admin/users)[/spiegelberg-festival/admin/users].

**Comment by peufo** [comment]
En lien avec #10

**Comment by peufo** [comment]
Cette issues existe déjà ici #11
