### ISSUE TITLE
Mise en place des champs personnalisés (text, nombre, boolean, choix)

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#36]
Laisser la possibilité aux responsables de mettre des commentaires sur les bénévoles non visibles fléaux. Genre, retard, no show, efficace mais relou avec les femmes, …

**Comment by peufo** [comment]
Hello @Patriedweg 

Tout est en place 🥳🥳🥳 et c'était un gros morceau.
Tu peux maintenant créer des champ personnalisés depuis [la page de configuration](https://benev.ch/spiegelberg-festival/admin/config).

Avec ce système, j'ai pu "déplacer" des infos du profil de base (général à la plateforme) vers le profil spécifique à l'évènement.

Pour ta demande, il te suffit maintenant de créer un champ que les membre ne peuvent pas lire.

**Comment by Patriedweg** [comment]
Trop fort 💪🏻 ! Bravo!!!!
