### ISSUE TITLE
Edition des pages: centrage du texte, couleurs

### ISSUE THREAD

**Issue by peufo** [peufo/benev#4]
J'utilise [https://editorjs.io/](https://editorjs.io/) pour l'édition des pages.
A voir si je trouve un moyen...

**Comment by Patriedweg** [comment]
Il y a un immense interligne entre les paragraphes d'une page créées. Je n'arrive pas à régler cet interligne. (voir l'onglet A table)

**Comment by peufo** [comment]
J'ai testé de rendre utilisant des listes à puces. 
C'est un peu mieux.

Je le trouve pas incroyablement pratique cet éditeur au final.
On verra si on reste la dessus.

**Comment by peufo** [comment]
Migration sur TipTap terminé. c'est beaucoup mieux.
