### ISSUE TITLE
Synthèse et documents opérationnels (checklist, planning)

### ISSUE THREAD

**Issue by peufo** [peufo/benev#40]
Un gros morceau qui peut être découpé suivant objectifs suivant :

 - [x] Adapter l'empilement des donnée (liste à choix multiple) voir [ce commentaire](https://github.com/peufo/benev/issues/17#issuecomment-1717333017)
- [X] Copie des la liste de membres pour exportation dans un tableur

**Comment by Patriedweg** [comment]
Et je me suis demandée aussi s'il y avait moyen d'extraire tous les mails pour écrire un mail à tous les bénévoles inscrits.

**Comment by peufo** [comment]
Hey, @Patriedweg 
Tu peux maintenant copier les données des membre pour facilement les coller dans un tableur. (avec l'icône à côté du champ de recherche)
J'ai que testé avec Google Sheet mais je pense pas qu'Excel pose problème.

C'est une solution simple pour sortir les données de l'application.
Mais si tu pensais à autre chose ou que ca comble pas totalement tes besoins, n'hésite pas à le dire ; )

**Comment by peufo** [comment]
On peut imaginer aller plus loin en configurant une synchronisation avec un Google Sheets.
Mais il me semble que ca ajoute beaucoup de complexité pour un bénéf assez limiter …

**Comment by Patriedweg** [comment]
C'est parfait comme ça !!!! Et effectivement pas besoin de lier à Google Sheets puisqu'on crée le tableau avec les infos qu'on veut.

**Comment by Patriedweg** [comment]
Gif de petit lapin qui fait des bonds ;-)
