### ISSUE TITLE
Les tranches horaires n'apparaissent pas correctement

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#43]
Lorsque je crée une tranche horaire et que je valide, la tranche n'est pas aux mêmes horaires que ce que j'ai rentré.
De plus, quand le bénévole veut s'inscrire les heures de début et de fin sont inversées.

**Comment by Patriedweg** [comment]
Ca marche chez moi en tous cas !

**Comment by peufo** [comment]
Les notifications par mail ont encore le mauvais fuseau horaire !!! 
Je vais corriger ca au plus vite.

**Comment by peufo** [comment]
J'ai forcer la bonne timezone... Pas très "international" mais ca ira très bien pour l'instant
