### ISSUE TITLE
Assigner une personne bénévole ou responsable

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#44]
Bon alors si on crée un nouveau bénévole et qu’on l’inscrit à un secteur, lui peut créer un nouveau secteur mais moi je ne peux pas le nommer responsable. Je peux uniquement me mettre moi comme responsable ou toi. Ca pourrait faire partie des priorité pour quand tu aurais le temps. Merci!

**Comment by peufo** [comment]
Yep, c'est une priorité.
Je clos cette issues car cette un doublon avec celle-là --> #26

**Comment by Patriedweg** [comment]
Ok mais tu arrives à m’expliquer comment nommer qqn responsable une fois qu’il est inscrit, je n’ai pas trouvé, désolée !!!

**Comment by peufo** [comment]
Je bosse à l'instant sur une vrais solution que j'espère être en place d'ici 2h. Je te donne des news dés que c'est fait.

**Comment by Patriedweg** [comment]
Ah trop désolée tu m’as dit que tu n’avais pas trop le temps… Courage et merci !!!!!

**Comment by peufo** [comment]
Hello, 

J'ai mis en place une solution. C'est pas encore optimal mais ca devrait faire le taf.
Tu peux maintenant partager un lien d'invitation pour devenir membre de l'évènement. Par exemple dans ton cas :  [benev.ch/spiegelberg-festival/invite](benev.ch/spiegelberg-festival/invite).

Une fois que quelqu'un est membre, tu peux le nommé comme responsable.

**Comment by Patriedweg** [comment]
Génial ! Je balance le lien à tous les responsables et c’est parti alors ?!? 
Merci !!!
Patricia
