### ISSUE TITLE
Supprimer la possibilité de créer un évènement sur la page d'accueil

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#45]
Il est très (trop) facile de créer un nouvel évènement depuis la page d'accueil. Il faudrait supprimer cette possibilité. Il faudrait que tu sois le seul à pouvoir créer un nouvel évènement, sinon ça va très vite être le bordel sur la plateforme ;-).
A ce propos, j'ai compris que seule la personne qui a créer l'évènement peut ajouter et modifier des secteurs, c'est bien juste?

**Comment by peufo** [comment]
Je suis d'accord, mais je pense que le problème viens du listing sur la page principal que je devrais modérer, et non pas de la création en elle même. 

(Oui, pour l'instant, seul le créateur/propriétaire d'un évènement a ces droits. Je mettrai un système de gestion plus clair à terme...)

**Comment by Patriedweg** [comment]
C'est très bien que sur le créateur de l'évènement puisse ajouter des secteurs :-)

**Comment by peufo** [comment]
La création de nouveau évènements ce fait maintenant depuis [son profil global](https://benev.ch/me).
L'ajout d'un 'état' de l'évènement #37 permettra déjà de cacher tout ce qui est brouillon.
+ La page d'accueil sera complètement revue
