### ISSUE TITLE
Inscriptions et responsables

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#47]
Salut, c'est trop bizarre, deux personnes se sont inscrites et je ne les vois pas du tout sur la plateforme et je n'ai rien reçu. Il s'agit de Valérie et Mélanie. 

Il y a aussi Aude et Lavinia qui se sont inscrite et je n'arrive pas à les nommer responsables. Alors qu'elles se sont inscrites à un évènement.

Redis-moi si tu peux.

Merci !!!!!

**Comment by peufo** [comment]
Hey, 
Pour l'instant, la liste de la page admin ne contient que les bénévoles et responsable actif (inscrit à une période ou responsable d'un secteur qui contient des périodes).
Je vais faire en sorte que tout les membres soit visible...

Je vois Aude et Lavinia dans la DB et la requête pour nommer les responsables est plutôt simple 🥲.
La liste est limité à 5 résultats. Tu tapes une recherche pour la sélectionner ?
Tu peux me confirmer le problème ?

**Comment by Patriedweg** [comment]
Peut-être on peut s’appeler 5 minutes ce sera plus simple pour se comprendre…
079.434.36.45
