### ISSUE TITLE
Secteurs par ordre alphabétique

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#49]
Y a-t-il moyen facile pour que les secteurs s'affichent par ordre alphabétique ou faut-il les créer dans l'ordre dans lequel on souhaite qu'ils s'affichent?

**Comment by peufo** [comment]
J'ai fait le tri par nom en dur dans la requête. 
Il faudrait quelque chose de plus flexible à terme...

**Comment by Patriedweg** [comment]
C'est parfait comme ça ! Ca ira nickel pour cette édition. Est-ce que tu peux faire la même chose pour la liste des bénévoles? Les classer par ordre alphabétique de prénom? Quand on en aura 300 ça sera plus facile de les retrouver.

**Comment by peufo** [comment]
C'est fait. Mais je pense qu'un champ de recherche serais pas mal utile. A faire...

**Comment by Patriedweg** [comment]
Oublie ma question sur l'ordre des tranches horaires. C'est moi qui n'ai pas les yeux en face des trous.
