### ISSUE TITLE
Nouvelle inscription bénévole 

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#51]
Hello! Je ne reçois pas de notification lorsqu’une personne s’inscrit sur la plateforme, seulement lorsqu’elle choisit une tranche horaire. Est-ce qu’il est possible de changer cela? Et comment savoir si son e-mail a été validé? Et, il y a Antoine Marchon qui s’est trompé de mail au moment de son inscription. Il a refait l’inscription mais je ne trouve pas sa deuxième inscription. Sais-tu ce qui a pu se passer? Merci!!!

**Comment by peufo** [comment]
Hey,

>  Et comment savoir si son e-mail a été validé?

Je viens d'ajouter l'info sur le profil de membre: 

![image](https://github.com/peufo/benev/assets/42370203/93481305-8757-4ae5-af06-31a804f13679)

> Je ne reçois pas de notification lorsqu’une personne s’inscrit sur la plateforme

La plateforme n'étant pas dédier à un seul évènement, c'est totalement normal.
Par contre, si il passe par le lien d'invitation à ton évènement, l'utilisateur pourra créer un compte puis directement rejoindre l'évènement. C'est la qu'il faut que j'ajoute une notification #50 .

> Il a refait l’inscription mais je ne trouve pas sa deuxième inscription

Il est simplement pas membre de l'évènement. --> https://benev.ch/spiegelberg-festival/invite

**Comment by Patriedweg** [comment]
Trop bien pour le mail validé ! Merci !

Donc pour Antoine Marchon, il faut que je lui demande de recréer un compte en passant bien par le mail d'invitation ? C'est bien ça ?

**Comment by peufo** [comment]
Il ne pourra pas recréer un compte avec le même email.
Il peut valider sont email quand il veut depuis son profil en cliquant sur l'icon juste à côté de son mail.

**Comment by Patriedweg** [comment]
Ben je ne vois que son compte avec la mauvaise adresse. Il m’a dit qu’il s’est inscrit à nouveau avec la bonne adresse mais je ne le trouve pas…

**Comment by peufo** [comment]
Il n'est pas membre de l'évènement avec son nouveau compte --> https://benev.ch/spiegelberg-festival/invite

**Comment by Patriedweg** [comment]
Ah oui tu m’avais déjà dit! Ok cette fois c’est compris!
