### ISSUE TITLE
orthographe

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#52]
J'essaye de te noter ici les trucs que je vois qui sont à corriger, ok ? (je suis maîtresse d'école)
- Quand tu rentre une nouvelle tranche horaire dans un secteur, il y a le Nombre de bénévole. Il faut mettre un s à bénévoles.
- Sur la page d'accueil des secteurs, je mettrais un s à Secteur (première colonne) car tout est au pluriel y compris le titre
- Sous la roue dentée pour la personne qui gère l'évènement, tu as des filtres, je mettrais un s à responsables car il y a un s à bénévoles
- Même page, sous synthèse Régimes particuliers corriger l'orthographe de particuliés en particuliers
- Message du mail lorsque l'inscription a été refusée: 
Ton inscription à la période de travail suivante a été refusée:
samedi.....
Retourne sur la plateforme si tu souhaites trouver une autre tranche horaire. Merci pour ta disponibilité !
(pour éviter le masculin générique)
- et quand l'inscription a été refusée sur la plateforme, il faut noter inscription refusée avec un e (quand on passe la souris sur la petite croix rouge)

**Comment by Patriedweg** [comment]
- Quand on rentre sur la page de profil, il y a un e en trop à Mon profile (titre)

**Comment by peufo** [comment]
Haha c'est clairement pas mon point fort.

C'est tous bon, merci pour les corrections.

(A l'exception de "s" de secteur )
