### ISSUE TITLE
nouveau truc bizarre

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#53]
Hey trop désolée mais quand je clique sur le nom d'un bénévole pour voir son profil, il y a le profil d'un autre bénévole qui apparait. Par exemple, je veux voir le profil de Noha Riedweg et c'est la carte d'Antoine Marchon qui sort...

**Comment by peufo** [comment]
Hey, 
Je n'arrive pas à reproduire, T'es sur Safari ?
Je viens changé le fonctionnement sur cette liste. C'est certainement corrigé.
Tu peux confirmé ?

**Comment by Patriedweg** [comment]
Je te dis si j’arrive à reproduire le bug. Je n’étais pas sur Safari.

**Comment by peufo** [comment]
@Patriedweg C'est en ordre ?
Je peux fermer l'issue ?

**Comment by Patriedweg** [comment]
Yes! Merci Patricia Riedweg Le 2 sept. 2023 à 16:15, Jonas Voisard ***@***.***> a écrit :﻿
@Patriedweg C'est en ordre ?
Je peux fermer l'issue ?
