### ISSUE TITLE
inscrire un bénévole

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#55]
Salut, y a-t-il un moyen d'inscrire un bénévole à un évènement sans qu'il s'inscrive lui sur la plateforme? Genre juste mettre son nom dans une tranche horaire. C'est pour savoir si on peut comptabiliser ces personnes sans leur demander de s'inscrire en ligne.

**Comment by peufo** [comment]
Ca rejoins un peu l'issue #33.
On peut imaginer "créer un compte invitation" en connaissant le mail, le nom et le prénom d'une personne.
Ca me semble nécéssaire de pouvoir le faire. J'ai mis la tâche en priorité.

**Comment by Patriedweg** [comment]
Ok super!

**Comment by Patriedweg** [comment]
Si le mail c’est pas obligatoire c’est mieux

**Comment by peufo** [comment]
L'email est essentiel pour identifier un utilisateur car le nom et le prénom ne suffisent pas.
Sans ca, impossible d'avoir un profil ( info complémentaire, liste d'inscription ).

**Comment by Patriedweg** [comment]
Ok merci!Patricia Riedweg Le 2 sept. 2023 à 16:22, Jonas Voisard ***@***.***> a écrit :﻿
L'email est essentiel pour identifier un utilisateur car le nom et le prénom ne suffisent pas.
Sans ca, impossible d'avoir un profil ( info complémentaire, liste d'inscription ).

**Comment by Patriedweg** [comment]
Salut! Est-ce que tu as pu avancer sur l’inscription par les organisateurs d’une personne bénévole qui ne veut pas le faire elle? On a plusieurs demandes et je me demande s’il faut trouver une autre solution.

**Comment by peufo** [comment]
Hello, c'est une question de 2-3 jours

**Comment by peufo** [comment]
Holà, c'est ""normalement"" tout bon.
J'ai pas trop respecter le délais que je m'étais fixé, j'en suis désolé.

Les périodes on maintenant une page dédié uniquement visible par les responsable.
Sur cette page, tu peux sélectionner un membre et l'inscrire.
Le reste du contenu de la page est un peu redondant avec le mode "ouvert/fermer" de la liste des périodes. A voir donc si on garde ce mode...

Si la personne que tu souhaite inscrire n'est pas encore membre, tu dois d'abord l'inviter avec le bouton "Inviter un nouveau membre".
Ensuite elle sera dispo dans la liste de sélection.

Comme dit plus haut, un mail est indispensable pour inviter un membre. 
Ceci dit, rien ne t'empêche de renseigner n'importe quoi. Mais cela implique que le compte ne sera pas récupérable et que personne ne pourra confirmer les inscriptions créer par un responsable.

Tu dois t'en douter avec les bugs que j'ai créer dernièrement, j'ai du toucher à pas mal de trucs.
Il y a donc de très fortes en chances que d'autre problèmes apparaisse.
Tu peux m'en faire part en créant des issues comme tu la fait ce matin ou directement ici.
Je la fermerai cette issue quand tu auras validé la fonctionnalité.

**Comment by Patriedweg** [comment]
Hello ! Alors j'ai pu tester et Valérie aussi. 

Je ne comprend pas ce que tu veux dire par: "Le reste du contenu de la page est un peu redondant avec le mode "ouvert/fermer" de la liste des périodes. A voir donc si on garde ce mode..." Donc je n'ai pas grand chose à dire là-dessus.

Sinon ce que j'ai compris: depuis une tranche horaire, tu invites un membre à s'inscrire soit en tapant son nom, soit en invitant un nouveau membre à s'inscrire. 

Pour le nouveau membre: ça semble tout bon. Il faut qu'il valide sa tranche depuis son mail mais le gros du boulot est fait à sa place et on peut imaginer de mettre notre mail à la place du sien et de le valider. J'en déduis qu'on peut créer autant de profils différents que l'on veut avec le même mail. Juste ?

Pour le nouveau membre: il y a un seul truc qui ne semblait pas clair, c'est le mot de passe à créer. Les deux personnes qui ont fait le test ont hésité. Est-ce qu'au lieu de Nouveau mot de passe, on mettrait : Créer un mot de passe ou Crée ton mot de passe ou Mot de passe à créer ?

Pour les membres déjà inscrit et les nouveaux membres: Tant que la personne n'a pas validé ou refusé son shift, la tranche horaire est bloquée et personne d'autre ne peut s'inscrire. Est-ce qu'on pourrait avoir la possibilité de la refuser si on voit qu'elle met trop de temps à s'inscrire ou de la valider si on sait que c'est tout bon?

Sinon ça semble tout bien !

**Comment by peufo** [comment]
> ...et on peut imaginer de mettre notre mail à la place du sien et de le valider. J'en déduis qu'on peut créer autant de profils différents que l'on veut avec le même mail. Juste ?

Non, le mail est unique sert à créer un utilisateur. Ensuite un membre est créer à partir de cette utilisateur.
Seul l'utilisateur ayant accès à ce mail pourra validé ces participations. 
Si un comptes n'est pas récupéré, ses inscriptions resterons non validés (en orange). 
Mais si c'est vraiment gênant, on peut imaginer une option "sans validation" dispo pour chaque membre.
Comme ca on pourra quand même avoir du vert partout : ) #72

> Pour le nouveau membre: il y a un seul truc qui ne semblait pas clair, c'est le mot de passe à créer. Les deux personnes qui ont fait le test ont hésité. Est-ce qu'au lieu de Nouveau mot de passe, on mettrait : Créer un mot de passe ou Crée ton mot de passe ou Mot de passe à créer ?
Tu veux dire qu'elles se sont mises dans le rôle de quelqu'un qui recoit une invitation ?
Effectivement, j'utilise la même page que quand tu clique sur "mot de passe oublié".
Je vais changer ca #71 

> Pour les membres déjà inscrit et les nouveaux membres: Tant que la personne n'a pas validé ou refusé son shift, la tranche horaire est bloquée et personne d'autre ne peut s'inscrire. Est-ce qu'on pourrait avoir la possibilité de la refuser si on voit qu'elle met trop de temps à s'inscrire ou de la valider si on sait que c'est tout bon?

Bien vu, on peux imager un statuts "annuler". #73
