### ISSUE TITLE
Vue d'ensemble: Créer un vue orientée secteur / inscription / charge

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#56]
Est-ce qu'il y a moyen d'afficher les tranches horaires avec le taux d'affichage par jour plutôt que par secteur ? Histoire de voir rapidement si on a assez de monde le samedi ou de voir que le jeudi on a personne au bar mais qu'on est complet en cuisine et qu'on peut éventuellement déplacer un bénévole.

**Comment by Patriedweg** [comment]
Peut-être que cette question va avec la demande d'extraction des données.

**Comment by Patriedweg** [comment]
#10 ?

**Comment by Patriedweg** [comment]
Oh oui ça se serait super d’avoir toutes les inscriptions en attente!
Et aussi de savoir que dans un secteur il n’y a personne et qu’il faut qu’on réagisse pour trouver du monde. 
merci!

**Comment by Patriedweg** [comment]
Pour info on a déjà ouvert les inscriptions aux premiers potes et on vise d’ouvrir tout public le 5 octobre ☀️

**Comment by peufo** [comment]
Le 5 septembre plutôt nan ? 
Il faut impérativement que je finisse la #6 d'ici la.

**Comment by Patriedweg** [comment]
Ah oui 5 septembre 😴. Trop bien pour la #6 si tu peux.

**Comment by peufo** [comment]
Je suis pas trop sur d'avoir compris ton message... 

Je suis en train de mettre en place une vue des secteurs et des périodes en mode "planning".
Les inscriptions en attente vont ressortir en orange dans la bar de progression des périodes de travail.

**Comment by Patriedweg** [comment]
Ah oui pardon j'ai écrit trop vite. 
Il me semblait avoir vu un total des tranches horaires sur tout le festival qq part avec le total de tranches horaires occupées mais je ne le vois plus. Peut-être je confonds.

Est-ce que les inscriptions en attentes vont être visibles depuis la vue Secteur ou faudra-t-il rentrer dans les secteurs. Pour le moment, je doit tout ouvrir pour voir où il reste des shifts à valider.

**Comment by Patriedweg** [comment]
Le planning j'ai vu ;-). Cela va faire rêver le responsable bénévole des 6 pompes ! C'est ce qu'il voulait.

**Comment by Patriedweg** [comment]
Pour la vue d'ensemble, moi j'aime bien l'histoire des filtres. Est-ce qu'on pourrait ajouter un filtre jour en plus de l'heure ? 
Pour voir tous ceux qui bossent le vendredi entre 14h et samedi 3h du matin par exemple.

**Comment by peufo** [comment]
En effet la dans synthèse il y avait le total des heures (inscrit / à faire).
Je l'ai retirer car les chiffres afficher n'étaient pas tout à fait correct. Mais je le remettrai correctement.

Le filtre sur la période fonctionne déjà de cette manière. Tu peux sélectionner deux dates différente sur le calendrier.

**Comment by Patriedweg** [comment]
Et pour moi ça va avec la #40

**Comment by Patriedweg** [comment]
[Technique.xlsx](https://github.com/peufo/benev/files/12774461/Technique.xlsx)
[Planning bénévoles bars Spiegel .xlsx](https://github.com/peufo/benev/files/12774464/Planning.benevoles.bars.Spiegel.xlsx)
[Repas bénévoles.xlsx](https://github.com/peufo/benev/files/12774466/Repas.benevoles.xlsx)

**Comment by Patriedweg** [comment]
Dans la synthèses, on a bien le nombre de bénévoles qui s'adapte à ce qu'on a sélectionné mais serait-il possible que le nombre du bas de la fraction s'adapte aussi (pour le moment c'est toujours le total général)? Je m'explique: j'aimerais savoir combien il manque de personnes le samedi (ou le jeudi,...) et là je ne sais pas comment trouver l'info facilement.
![Capture d’écran 2023-09-30 à 13 32 07](https://github.com/peufo/benev/assets/142038314/418e423c-11e2-4d27-a85b-bacdc4a3103f)

**Comment by Patriedweg** [comment]
Quand je télécharge les données et que je les colle dans un google sheet, il y a une information par colonne ce qui est super. Seulement, j'ai des infos qui viennent se mettre en deuxième ligne comme les commentaire et là ça met le Bronx dans le tableau. Est-ce qu'il y a moyen d'avoir un champ par colonne ?

**Comment by peufo** [comment]
> Quand je télécharge les données et que je les colle dans un google sheet, il y a une information par colonne ce qui est super. Seulement, j'ai des infos qui viennent se mettre en deuxième ligne comme les commentaire et là ça met le Bronx dans le tableau. Est-ce qu'il y a moyen d'avoir un champ par colonne ?

Ha merde, il faut que je supprime les retours à la ligne dans les valeurs.

**Comment by Patriedweg** [comment]
Je n'arrive plus trop à suivre mais on se voit en vrai bientôt. Alerte-moi s'il y a une question qui nécessite une réponse urgente. merci !

**Comment by peufo** [comment]
Je pense que l'onglet "planning" répond à la problématique de à cette issue.

Le reste est plutôt lien au document opérationnel --> #40
