### ISSUE TITLE
Cellules du profil trop petites

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#58]
Les cellules du profil (compétences, commentaire et infos internes) sont très petites. Est-il possible de les agrandir et/ou de diminuer le texte pour pouvoir lire leur contenu?

**Comment by peufo** [comment]
Yep, je dois ajouter l'option "texte long" dans les champs libre.

**Comment by Patriedweg** [comment]
Si c'est facile à faire, je veux bien que tu t'en occupes car pour le moment c'est pas facile à lire.

**Comment by peufo** [comment]
Hey, facile veut pas forcément dire rapide désolé ^^
Je suis sur le point de finir #55 avant, puis je fait ca.
Il y a aussi les listes à chois qui pourrait être de type dropdown... à voir

**Comment by Patriedweg** [comment]
Oups ok désolée! Tu as le droit, plutôt le devoir de nous remettre à l’ordre moi et mon enthousiasme parce que je n’ai aucune idée des heures de boulot que ca représente pour toi! Donc merci!!!

**Comment by peufo** [comment]
Hey, c'est fait.
T'inquiète, ton enthousiasme est le bienvenu ; )

**Comment by Patriedweg** [comment]
C'est parfait !
