### ISSUE TITLE
shifts refusés

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#59]
Il semblerait qu'il y ait des inscriptions qui passent directement en statut "refusé" plutôt que "en attente de validation". J'ai vu cela au secteur Bar.

**Comment by peufo** [comment]
C'est plutôt étonnant comme bug. Je soupçonne une mauvaise manip.
Il faut trouver un moyen de reproduire la cas, sinon, c'est pratiquement impossible a résoudre pour moi.

**Comment by Patriedweg** [comment]
Exemple avec Alexandre Kaiser. Il n’y a eu aucune manip et ses shifts sont en statu refusés

**Comment by peufo** [comment]
Mea culpa !!! Heureusement que t'as vu ca.
Les données sont bonnes mais il avait un croisement entre les inscription à l'affichage des profils (admin et personnel).

**Comment by Patriedweg** [comment]
Autre exemple avec Jonas Kilcher qui avait deux shifts validés alors que je n'avais rien fait

**Comment by Patriedweg** [comment]
Ah trooooop soulagée !!! Merci !!!

**Comment by peufo** [comment]
C'est possible qu'il y ai eu des croisement du coup 😬.

Validation ou refus d'inscription qui n'était celle que tu pensais si tu bossais depuis les profils...
Vraiment désolé pour le taf supplémentaire.

**Comment by Patriedweg** [comment]
C’est corrigé maintenant? Je peux vérifier?Patricia Riedweg Le 5 sept. 2023 à 21:45, Jonas Voisard ***@***.***> a écrit :﻿
C'est possible qu'il y ai eu des croisement du coup 😬.
Validation ou refus d'inscription qui n'était celle que tu pensais si tu bossais depuis les profils...
Vraiment désolé pour le taf supplémentaire.

**Comment by Patriedweg** [comment]
Est-ce que c'est corrigé maintenant ? Si oui c'est cool, merci !!
