### ISSUE TITLE
Workflow de l'inscription d'un membre

### ISSUE THREAD

**Issue by peufo** [peufo/benev#6]
L'organisateur devrait pouvoir définir ces exigences de participation pour chaque équipe:
- Un âge minimum
- Assurance accident
- Adresse complété
- Numéro de téléphone complété

Comme ca, il peut être demander à l'utilisateur de compléter sont profil AVANT de s'inscrire.

**Comment by Patriedweg** [comment]
Ce serait bien ! TOUS les bénévoles qui s'inscrivent pour l'instant oublient tout simplement de compléter leur profil et souvent même de valider leur adresse e-mail. S'il pouvait y avoir un petit message d'erreur du type: "As-tu validé ton adresse e-mail et complété ton profil avant de t'inscrire ?" Ce serait top !

**Comment by peufo** [comment]
Le formulaire qui demande les informations complémentaire des membres est maintenant afficher dés l'adhésion d'un membre.
Ils n'ont donc plus besoin d'aller eux-mêmes sur leur profil.

Ce n'est pas une validation automatique, mais ca répond déjà a une bonne partie du problème.
Je retire le label prioritaire te la tâche.

**Comment by Patriedweg** [comment]
Super! Je testerai ce soir ou demain Patricia Riedweg Le 2 sept. 2023 à 16:13, Jonas Voisard ***@***.***> a écrit :﻿
Le formulaire qui demande les informations complémentaire des membres est maintenant afficher dés l'adhésion d'un membre.
Ils n'ont donc plus besoin d'aller eux-mêmes sur leur profil.
Ce n'est pas une validation automatique, mais ca répond déjà a une bonne partie du problème.
Je retire le label prioritaire te la tâche.
