### ISSUE TITLE
Bar halle cantine 

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#61]
Hello! On a perdu toutes les tranches horaires du bar de la halle cantine. Tu as une idée de ce qui a pu se passer? Les gens qui sont respo me disent qu’ils n’ont rien touché

**Comment by peufo** [comment]
WTF !!!
C'est vraiment chelou, je comprend pas ce qui à pu ce passer.
J'ai un backup qui date de hier matin. Je vais les restaurer à la main...

Faudra que je mette en place un historique

**Comment by peufo** [comment]
C'est en ordre, mais ca reste plutôt inquiétant.
Je dois mettre en place un historique #62
