### ISSUE TITLE
halle cantine

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#63]
Il manque encore cette inscriptions:

Bonne nouvelle ! Laura Roux souhaite renforcer le secteur Bar de la Halle Cantinedurant la période suivante :vendredi, 06.10.2023 20:00 – samedi, 07.10.2023 00:00Verifie ses informations et valide son inscription si tout te semble ok.
--

Bonne nouvelle ! 
Laura Roux souhaite renforcer le secteur Bar de la Halle Cantine durant la période suivante :

vendredi, 06.10.2023 20:00 – samedi, 07.10.2023 00:00
Verifie [ses informations](https://benev.ch/spiegelberg-festival/admin/members/clm61da9y0001l408rlkjp36t) et [valide son inscription](https://benev.ch/spiegelberg-festival/teams/clm0kt8go000dl5083dsveiib?periodOpen=clm0ku599000fl5086dbjfvgp) si tout te semble ok.

**Comment by Patriedweg** [comment]
Tu peux la rajouter ou je demande à la personne de le faire ? Je la connais bine, je peux lui demander de se réinscrire.

**Comment by peufo** [comment]
Ouf ! Ca me rassure un max.
Volontiers si tu peux lui demander de refaire son inscription, c'est plus simple que de la faire à la main.
Elle a du être faite après le backup que j'ai récupéré, c'est pour ca que je l'ai pas eu.

Tu pourras bientôt inscrire toi même des gens sur des tranches, j'y bosse activement.
