### ISSUE TITLE
Assurance accident

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#64]
Hello,
Il y a environ la moitié des bénévoles qui ne cliquent pas sur le bouton de l'assurance accident. Ce qui me demande d'écrire à chaque personne. Est-ce qu'on arrive à modifier ainsi.

Assurance accident
0 J'ai.
0 Je n'ai pas.

**Comment by peufo** [comment]
Tu peux créer/éditer toi-même un champ de type "liste de choix" dans "configurations" >"Profil des membres".
Le problème ici c'est que si tu changes le type du champ existant, tu vas perdre les infos déjà renseignées.
Il faut donc créer un autre champ puis ouvrir chaque profil pour cocher la bonne options. Ensuite tu pourras supprimer l'ancien champ.

C'est un peu contraignent je sais mais j'ai pas de solution plus simple pour l'instant.
Ca devrait prendre quelque minutes pour une soixantaine de membre.
