### ISSUE TITLE
Bug vue membres et champs !!!!

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#65]
Hello ! Une page blanche s'affiche lorsque je clique sur un membre (et rien d'autre). Est-ce que c'est parce que tu travailles sur la plateforme ?

**Comment by Patriedweg** [comment]
J'ai créé un nouveau champ pour indiquer les concerts auxquels les bénévoles ont droit. Mais je n'arrive plus à le modifier. En fait je n'arrive plus à faire grand chose avec la plateforme...

**Comment by peufo** [comment]
C'est corrigé, il y avait une limitation sur le nombre d'options possible
