### ISSUE TITLE
Modification tranches horaires

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#66]
Hello,

On n'arrive plus à modifier les tranches horaires, ni les heures, ni le nombre de bénévoles. On arrive juste à les supprimer et en recréer d'autres. Est-ce normal ?

**Comment by peufo** [comment]
Non évidement,

J'ai du chambouler pas mal de trucs pour l'implémentation de l'inscription par les responsables... 
J'ai les mains dedans en ce moment même, je te redis dés que c'est ok.

**Comment by peufo** [comment]
C'est corrigé normalement.
Désolé pour le dérangement

**Comment by Patriedweg** [comment]
Oui ça joue ! Merci !
