### ISSUE TITLE
Personnalisation de l'ordre et de l'apparence des champs libres

### ISSUE THREAD

**Issue by peufo** [peufo/benev#68]

**Comment by Patriedweg** [comment]
Hello, 
Valérie a ajouté les repas du mercredi et du jeudi mais du coup les jours ne sont plus dans l'ordre. Est-ce qu'il va être possible de modifier l'ordre des items ou est-ce qu'il faut recréer un champ et recopier les données ? Ou vivre avec le fait que les jours ne sont pas dans le bon ordre.
![Capture d’écran 2023-09-22 à 12 26 48](https://github.com/peufo/benev/assets/142038314/127c5315-d492-47c6-ae83-650b1e3fe5a5)

**Comment by peufo** [comment]
Tu peux maintenant réordonner les liste d'options.
Je viens de l'implémenter.

**Comment by peufo** [comment]
On peut maintenant donner l'ordre qu'on veut au champs libre.
Le profile à un peu plus fière allure.

Pour l'apparence, c'est pas prioritaire. Je verrai ca plus tard.
