### ISSUE TITLE
Ajouter la possibilité de lier des champs libre aux inscriptions

### ISSUE THREAD

**Issue by peufo** [peufo/benev#69]
Exemple d'utilisation: 
- Check de présence
- Check de compensation 
- Commentaire sur le shift effectué

**Comment by Patriedweg** [comment]
Oui la check list ce serait vraiment super !!! 
Et si on pouvait sortir une liste d'invitations par concert ce serait top !!!

**Comment by Patriedweg** [comment]
Genre pour les repas, pour le moment, c'est un peu le casse-tête et on ne sait pas qui de tous ces gens est végétarien ou autre:
![Capture d’écran 2023-09-15 à 16 41 26](https://github.com/peufo/benev/assets/142038314/574986f9-bd68-489d-871d-2225257d2867)

**Comment by peufo** [comment]
Ca me semble être des problème qui peux être résolu en ajoutant des filtres sur les champs libre --> #74 
1. Tu filtres les membres sur le repas que tu veux voir
2. Tu regardes la synthèse des régimes 

Même principe pour la liste d'invitation

**Comment by peufo** [comment]
@Patriedweg  la #74 est terminé, tu peux tester quand tu veux : )

**Comment by Patriedweg** [comment]
Franchement c'est la classe ! 
Hem, tu crois qu'on pourrait exporter les listes créées avec les filtres dans un doc lisible par tout le monde, genre un googlesheet ou même un doc ? Par exemple pour le cuisinier ou les responsables de secteurs ? 
Gif de bébé chat avec de très grands yeux et les oreilles en arrière.

**Comment by Patriedweg** [comment]
PS: je viens de découvrir le petit bouton "compter par combinaison de valeurs", c'est parfait !!!! Merci !!!

**Comment by peufo** [comment]
> Gif de bébé chat avec de très grands yeux et les oreilles en arrière.

Haha dur de résister.
J'ai ajouter la copie des données dans le presse papier dans les tâches de la #40 .
Une fois copier, il suffit des coller les données sur Excel ou sur Google Sheet.
Si c'est pas ce que tu imaginais, je t'invites donnée plus de détails directement sur la #40.

**Comment by peufo** [comment]
Finalement pas une si bonne idée.
Je vais plutôt mettre en place des valeur en dur.
Ca fera parti de la #40.

- Check de présence --> sur l'inscription
- Check de compensation --> sur le membre
- Commentaire sur le shift effectué --> sur l'inscription
