### ISSUE TITLE
Membres inscrits qui n'ont pas de shifts

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#70]
J'ai remarqué que les membres inscrits qui n'avaient pas de shifts n'étaient pas listés dans les membres à la page récapitulative. Et je voulais savoir comment accéder à ces profils pour leur mettre les compensations. Par exemple, comment je ferais pour te mettre des repas et invitations au concerts et est-ce que tu apparaitra dans le tableau récapitulatif?

**Comment by peufo** [comment]
C'est effectivement que les membre actif qui sont visible.
Je suis un peu embêté, tout les filtres repose sur les inscriptions ou les responsabilités...

Je peux afficher tout le monde si aucun filtre n'est utilisé.

**Comment by peufo** [comment]
C'est fait
