### ISSUE TITLE
feat: annulation des inscriptions

### ISSUE THREAD

**Issue by peufo** [peufo/benev#73]

**Comment by Patriedweg** [comment]
Valérie s'est trompée de mail en inscrivant un bénévole. Elle demande s'il est possible de corriger le mail.

**Comment by peufo** [comment]
C'est en place !

Les responsable peuvent maintenant annuler ( puis éventuellement rétablir ) les inscription qu'ils ont créer.
Même chose pour les membres qui peuvent également annuler les inscriptions qu'il ont créer.

A valider, on est pas à l'abri d'une surprise.
Je sais que certaine notifs par mails ne passe pas, ca fait plus d'une semaine que j'ai contacter Infomaniak mais ils sont pas réactif.
