### ISSUE TITLE
John No

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#75]
Hello,

On a un John No qui était inscrit et qui a disparu. Je pense que c'était un faux nom. Et son profil a complètement disparu. Je me dis que je te le signale en espérant que ce ne soit pas un petit malin qui essaye de pirater la plateforme. Ou alors c'est l'un de tes faux profils ?

**Comment by peufo** [comment]
Hey,
C'est possible que c'était John Do plutôt ?
C'était effectivement un compte teste, désolé que vous l'ayez vue passé.

**Comment by Patriedweg** [comment]
Ah oui John Do !

**Comment by Patriedweg** [comment]
Je suis rassurée
