### ISSUE TITLE
Suppression d'un membre

### ISSUE THREAD

**Issue by peufo** [peufo/benev#76]

**Comment by Patriedweg** [comment]
Est-ce que tu pourrais supprimer les profils suivants:
Beuetbryan@gmail.com (j’ai oublié le R de Beuret) (attention il y a un Bryan Beuret avec 38.5 périodes qu'il ne faut pas effacer)
val_2345@yahoo.com (Steve Gay Crosier mais attention il y en a 2, il faut supprimer celui qui n'a aucune période)
Les deux Valérie Boillat test
Félicien Lia
Essai Bison
Sophie Dolto

Merci !

**Comment by peufo** [comment]
C'est fait

**Comment by Patriedweg** [comment]
Merci !
Pourrais-tu supprimer
Lydia Mbolela
Sarah Frund
Corinne Beuret avec le mail .ch (il y a une autre avec .com qu'il faut garder car c'est sa bonne adresse). 
Merci d'avance
