### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#77]
On a Jeff qui fait -15,5 heure. Il a une dette envers toi ?

**Comment by Patriedweg** [comment]
![Capture d’écran 2023-09-22 à 13 25 51](https://github.com/peufo/benev/assets/142038314/9806281b-4cc1-4aac-921a-56694fe4a938)

**Comment by peufo** [comment]
Certaines périodes étaient invalides. (la fin était avant le début).
J'ai oublié de contrôler la validité lors de la mise à jour des périodes.

J'ai corrigé les périodes en question et j'ai ajouté le check lors de l'édition.

**Comment by Patriedweg** [comment]
ah ok merci !
