### ISSUE TITLE
Message d'accueil !!!

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#78]
![WhatsApp Image 2023-09-23 at 11 27 08](https://github.com/peufo/benev/assets/142038314/b5f69571-b892-48f6-9e1d-e66a3c065952)

**Comment by Patriedweg** [comment]
Désolée mais il y a des fautes d'orthographe. Je relis volontiers les messages avant que tu les publies si jamais.

**Comment by Patriedweg** [comment]
Spiegelberg Festival

Bienvenue dans notre équipe bénévole

Salut XXX,
Tu fais désormais partie des nôtres. Tu peux maintenant compléter ton [profil](https://benev.ch/spiegelberg-festival/me/profile) si ce n'est déjà fait et t'inscrire aux tranches horaires qui t'intéressent en consultant les différents [secteurs](https://benev.ch/spiegelberg-festival/teams).

Les responsables qui ont accès à ton profil pourront ensuite valider tes tranches horaires et prendre contact avec toi le moment venu. 

Tes entrées aux concerts et repas seront visibles dans ton profil.

Un énorme merci pour ta disponibilité !

Toute l'équipe du Spiegelberg Festival

**Comment by Patriedweg** [comment]
Voici le texte que je propose.
Pour la validation des mails on a laissé tomber parce que ce n'est pas très clair. J'avais compris qu'au moment de l'inscription un mail était automatiquement envoyé pour valider le mail. Mais en fait il faut cliquer sur la croix orange, aller dans son mail et valider... Donc soit mettre dans le mail d'accueil un lien pour valider le mail directement ou soit laisser tomber et on réfléchit pour l'année prochaine.

**Comment by Patriedweg** [comment]
Y a-t-il d'autres textes envoyés automatiquement ?

**Comment by peufo** [comment]
> Désolée mais il y a des fautes d'orthographe. Je relis volontiers les messages avant que tu les publies si jamais.

> Y a-t-il d'autres textes envoyés automatiquement ?

Normal, je suis un brèle en horographe. Tu peux consulter tout [les model de mails](https://github.com/peufo/benev/tree/main/src/lib/email) et tu peux même proposer des modifications.

> Tes entrées aux concerts et repas seront visibles dans ton profil.

J'ai corrigé selon ta demandes, mais je peux pas mettre cette phrase car elle est spécifique à la configuration du Spiegelberg.
Faudrait mettre en place un système de mails personnalisé #79 

> Pour la validation des mails on a laissé tomber parce que ce n'est pas très clair. J'avais compris qu'au moment de l'inscription un mail était automatiquement envoyé pour valider le mail.

C'est le cas, le mail de bienvenue contient un lien pour directement valider son mail.
Le problème c'est qu'Infomaniak m'empêche de les envoyer je comprend pas pourquoi. (et c'est le cas pour pas mal d'autre notifs)
Pourtant, j'ai adhérer au service mail payant... J'ai un ticket ouvert depuis deux semaines, y réagissent pas ca me gonfle.

**Comment by Patriedweg** [comment]
Ok alors on laisse tomber la phrase sur les contreparties ! On va viser les trucs prioritaires jusqu'au festival et ça ne l'est pas. Et après le festival, si tu veux continuer à améliorer l'outil, je veux bien continuer à te faire des retours :-)
