### ISSUE TITLE
Modification des textes automatiques

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#80]
EmailAcceptInviteNotification.svelte

fait désormais partie de l'évènement. (partie avec un e et évènement avec un accent grave sur le 2e e)

**Comment by Patriedweg** [comment]
EmailLayout.svelte

Gestion des bénévoles par (s à bénévoles)

**Comment by Patriedweg** [comment]
EmailNewSubscribe.svelte

Tu es invité à rejoindre l'équipe de bénévoles durant la période de travail suivante : (Mettre Nous t'invitons pour éviter le participe passé qui doit s'accorder si c'est une fille mais je ne sais pas si ça joue avec le ton que tu veux donner)

**Comment by Patriedweg** [comment]
Il y aurait encore le Désolé qui normalement s'accorde si c'est féminin, mais celui-là je te le laisse parce que je n'ai pas mieux. ;-)

**Comment by Patriedweg** [comment]
Franchement ce n'est pas si mal pour quelqu'un qui n'a pas d'affinité avec l'orthographe !

**Comment by peufo** [comment]
Merci pour les corrections, c'est appliqué
