### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#81]
On n'arrive plus à ajouter des tranches horaires ni à modifier des descriptifs de secteurs.

Merci pour ton aide !

**Comment by Patriedweg** [comment]
Et je n'ai plus la roue dentée.
Je suis sur Chrome.

**Comment by Patriedweg** [comment]
En fait je ne peux plus rien faire... Comme si je n'étais plus admin.

**Comment by Patriedweg** [comment]
Et quand je me mets sur mon autre profil Patricia, je n'arrive pas à voir les shifts auxquels je me suis inscrite...

**Comment by Patriedweg** [comment]
Ahhhhh désolée je m'étais trompée de compte !!!

**Comment by peufo** [comment]
Toutes les validations de formulaire avait un petit problème.
Vraiment désolé pour ca.

Tu peux me dire si ca joue maintenant ?

**Comment by Patriedweg** [comment]
Oui ça joue ! Merci pour ta réactivité !
