### ISSUE TITLE
validation de profil

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#83]
quand on clique sur Tu peux trouver toutes ses informations [sur son profil.](https://benev.ch/spiegelberg-festival/admin/members/clmyzwbb20001m908sbebea4m) dans le mail, on arrive sur une page d'erreur. Peut-être un petit lien à réparer?

**Comment by peufo** [comment]
Les liens vers les profiles ont changés avec la dernière mise à jour. 
C'est passé de /admin/members/[id]  à "/admin/manage/members/[id]"

Les nouveaux mail envoyé sont ok. Mais les anciens on des liens morts.
Si c'est vraiment grave, je peut faire une redirection. Sinon on laisse coulé. A toi de dire

**Comment by Patriedweg** [comment]
Ok ce n'est vraiment pas grave. On laisse couler !
