### ISSUE TITLE
Photo

### ISSUE THREAD

**Issue by Patriedweg** [peufo/benev#86]
Hello, j'ai demandé à Antoine Marchon, directeur technique au Spiegelberg Festival s'il avait des retours à faire sur la plateforme. Il a dit qu'elle était super. Il aimerait que les bénévoles puissent télécharger une photo d'eux pour les badges ou juste pour que les respos puissent mettre un visage sur un nom.
Il a proposé également de mettre sur chaque shift une indication du lieu de rendez-vous pour la période mais ça je ne sais pas si je suis convaincue. Il me semble qu'on a déjà eu l'occasion d'échanger à ce propos.

**Comment by peufo** [comment]
Je suis entrain de changer l'hébergement du site pour pouvoir importer des photos. 
Le site est inaccessible un petit moment.

**Comment by Patriedweg** [comment]
C'est tout bien comme ça !
